"""Runner-level tests for
scripts/bootstrap/sl0025_breadth_enrichment_entry_decision_runner.py.

``run_verify`` is exercised first against the real committed retained
SLICE-0025 package (a regression check that the checked-in
``research/stage3/sl0025-breadth-enrichment-entry/`` documents remain
self-consistent and reproduce from the live SLICE-0018/0020/0021/0022/0023/
0024 artifacts with zero drift), then against tampered copies (written to
``tmp_path`` via monkeypatched module path constants, so the real committed
package is never touched by tests) to prove the offline verifier fails
closed. ``run_assemble`` is exercised once as a regression check that it
reproduces the real committed retained package byte-for-byte.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[2]
RUNNER_PATH = ROOT / "scripts" / "bootstrap" / "sl0025_breadth_enrichment_entry_decision_runner.py"


def _load_runner_module() -> Any:
    spec = importlib.util.spec_from_file_location(
        "hullq_sl0025_breadth_enrichment_entry_decision_runner_test_import", RUNNER_PATH
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def runner() -> Any:
    return _load_runner_module()


def _copy_retained_package(runner: Any, tmp_path: Path) -> None:
    for src in runner.SL0025_DIR.iterdir():
        if src.is_file():
            (tmp_path / src.name).write_bytes(src.read_bytes())

    runner.SL0025_DIR = tmp_path
    runner.DECISION_INPUT_PATH = tmp_path / "decision_input.json"
    runner.DECISION_INPUT_SCHEMA_PATH = tmp_path / "decision_input_schema.json"
    runner.DECISION_RESULT_PATH = tmp_path / "decision_result.json"
    runner.DECISION_RESULT_SCHEMA_PATH = tmp_path / "decision_result_schema.json"
    runner.REPORT_PATH = tmp_path / "REPORT.md"
    runner.ARTIFACT_DIGESTS_PATH = tmp_path / "ARTIFACT-DIGESTS.json"
    runner.ARTIFACT_DIGESTS_SCHEMA_PATH = tmp_path / "ARTIFACT-DIGESTS.schema.json"


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


# ---------------------------------------------------------------------------
# Regression: the real committed retained package verifies clean
# ---------------------------------------------------------------------------


def test_run_verify_passes_against_real_committed_retained_package(runner: Any) -> None:
    runner.run_verify()  # must not raise SystemExit


def test_run_assemble_reproduces_real_committed_package_byte_for_byte(
    runner: Any, tmp_path: Path
) -> None:
    original = {p.name: p.read_bytes() for p in runner.SL0025_DIR.iterdir() if p.is_file()}
    _copy_retained_package(runner, tmp_path)
    runner.run_assemble()
    for name, original_bytes in original.items():
        if name in {
            "decision_input_schema.json",
            "decision_result_schema.json",
            "ARTIFACT-DIGESTS.schema.json",
        }:
            continue  # schemas are not regenerated by the assemble step
        rewritten = (tmp_path / name).read_bytes()
        assert rewritten == original_bytes, f"{name} changed on re-assembly"


# ---------------------------------------------------------------------------
# Tamper resistance
# ---------------------------------------------------------------------------


def test_run_verify_fails_closed_on_tampered_decision_field(runner: Any, tmp_path: Path) -> None:
    _copy_retained_package(runner, tmp_path)
    decision_result = json.loads(runner.DECISION_RESULT_PATH.read_bytes())
    decision_result["decision"] = "CONTINUE_STAGE_3_2_ONLY"
    _write_json(runner.DECISION_RESULT_PATH, decision_result)

    with pytest.raises(SystemExit):
        runner.run_verify()


def test_run_verify_fails_closed_on_tampered_canonical_count(runner: Any, tmp_path: Path) -> None:
    _copy_retained_package(runner, tmp_path)
    decision_input = json.loads(runner.DECISION_INPUT_PATH.read_bytes())
    decision_input["reproduced_accepted_boundary"]["accepted_canonical_boat_models"] = 1771
    _write_json(runner.DECISION_INPUT_PATH, decision_input)

    with pytest.raises(SystemExit):
        runner.run_verify()


def test_run_verify_fails_closed_on_fabricated_adapter_ready_count(
    runner: Any, tmp_path: Path
) -> None:
    _copy_retained_package(runner, tmp_path)
    decision_input = json.loads(runner.DECISION_INPUT_PATH.read_bytes())
    decision_input["reproduced_accepted_boundary"]["sl0020_adapter_ready_archive_sources"] = 3
    _write_json(runner.DECISION_INPUT_PATH, decision_input)

    with pytest.raises(SystemExit):
        runner.run_verify()


def test_run_verify_fails_closed_on_fabricated_auto_admit_count(
    runner: Any, tmp_path: Path
) -> None:
    _copy_retained_package(runner, tmp_path)
    decision_input = json.loads(runner.DECISION_INPUT_PATH.read_bytes())
    decision_input["reproduced_accepted_boundary"]["sl0022_auto_admit_from_57"] = 5
    _write_json(runner.DECISION_INPUT_PATH, decision_input)

    with pytest.raises(SystemExit):
        runner.run_verify()


def test_run_verify_fails_closed_on_fabricated_sl0024_threshold_recommendation(
    runner: Any, tmp_path: Path
) -> None:
    _copy_retained_package(runner, tmp_path)
    decision_input = json.loads(runner.DECISION_INPUT_PATH.read_bytes())
    decision_input["reproduced_accepted_boundary"]["sl0024_final_recommendation"] = (
        "FULL_409_VERIFICATION_CAMPAIGN_CANDIDATE"
    )
    _write_json(runner.DECISION_INPUT_PATH, decision_input)

    with pytest.raises(SystemExit):
        runner.run_verify()


def test_run_verify_fails_closed_on_tampered_crosswalk_count(runner: Any, tmp_path: Path) -> None:
    _copy_retained_package(runner, tmp_path)
    decision_input = json.loads(runner.DECISION_INPUT_PATH.read_bytes())
    decision_input["reproduced_accepted_boundary"]["historical_qid_to_hullq_id_mappings"] = 1773
    _write_json(runner.DECISION_INPUT_PATH, decision_input)

    with pytest.raises(SystemExit):
        runner.run_verify()


def test_run_verify_fails_closed_when_decision_changes_without_relevant_input_change(
    runner: Any, tmp_path: Path
) -> None:
    _copy_retained_package(runner, tmp_path)
    decision_result = json.loads(runner.DECISION_RESULT_PATH.read_bytes())
    # Flip only the decision, leaving every mechanically-relevant input byte
    # unchanged -- the recomputation must disagree and fail closed.
    decision_result["decision"] = "BLOCKED_ON_ACCEPTED_STATE"
    _write_json(runner.DECISION_RESULT_PATH, decision_result)

    with pytest.raises(SystemExit):
        runner.run_verify()


def test_run_verify_fails_closed_on_artifact_digest_tampering(runner: Any, tmp_path: Path) -> None:
    _copy_retained_package(runner, tmp_path)
    runner.REPORT_PATH.write_bytes(runner.REPORT_PATH.read_bytes() + b"\ntampered\n")

    with pytest.raises(SystemExit):
        runner.run_verify()


# ---------------------------------------------------------------------------
# Coherent tamper: a candidate is altered so the mechanical decision itself
# would change, and every dependent retained document (decision_result,
# REPORT.md, ARTIFACT-DIGESTS.json) is regenerated to stay internally
# consistent with that tamper -- proving --verify still fails because the
# retained candidate derivation disagrees with the independently rebuilt
# candidate set, not merely because some byte happens not to match.
# ---------------------------------------------------------------------------


def test_run_verify_fails_closed_on_coherent_candidate_tamper(
    runner: Any, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    from hullq.bootstrap.sl0025_breadth_enrichment_entry_decision import (
        ARTIFACT_DIGEST_COVERED_FILENAMES,
        build_decision_result_document,
    )

    _copy_retained_package(runner, tmp_path)

    decision_input = json.loads(runner.DECISION_INPUT_PATH.read_bytes())
    alt_route = next(
        c
        for c in decision_input["known_breadth_path_candidates"]
        if c["name"] == "sl0021_sl0022_alternative_wikidata_route"
    )
    # Flip the two fields that gate qualification for this candidate: no
    # longer "already executed", and a yield comfortably above the >=100
    # threshold. Every other candidate/boundary field is left byte-identical
    # to the real accepted package.
    alt_route["already_executed"] = False
    alt_route["likely_incremental_yield"] = 150
    alt_route["qualifies"] = True
    _write_json(runner.DECISION_INPUT_PATH, decision_input)

    generated_at = decision_input["generated_at"]
    decision_result = build_decision_result_document(
        generated_at=generated_at, decision_input=decision_input
    )
    # The tamper really does flip the mechanical decision -- otherwise this
    # would not be testing the coherence attack described in the amendment.
    assert decision_result["decision"] == "CONTINUE_STAGE_3_2_ONLY"
    assert decision_result["qualifying_breadth_path"]["name"] == (
        "sl0021_sl0022_alternative_wikidata_route"
    )
    _write_json(runner.DECISION_RESULT_PATH, decision_result)

    report = runner._build_report(decision_input, decision_result)
    runner.REPORT_PATH.write_bytes(report.encode("utf-8"))

    digests = {}
    for name in ARTIFACT_DIGEST_COVERED_FILENAMES:
        digests[name] = "sha256:" + hashlib.sha256((tmp_path / name).read_bytes()).hexdigest()
    artifact_digests = {
        "schema_version": "sl0025-artifact-digests-v1",
        "generated_at": generated_at,
        "excludes_self": "ARTIFACT-DIGESTS.json",
        "digests": digests,
    }
    _write_json(runner.ARTIFACT_DIGESTS_PATH, artifact_digests)

    with pytest.raises(SystemExit):
        runner.run_verify()

    output = capsys.readouterr().out
    assert "known_breadth_path_candidates" in output


# ---------------------------------------------------------------------------
# sl0024_threshold_required source-drift: the reproduced side reads the
# accepted SLICE-0024 module constant independently of the fixed literal --
# a drift there must still be caught by --verify.
# ---------------------------------------------------------------------------


def test_run_verify_fails_closed_on_threshold_required_source_drift(
    runner: Any, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import hullq.bootstrap.sl0025_breadth_enrichment_entry_decision as sl0025_module

    _copy_retained_package(runner, tmp_path)
    monkeypatch.setattr(sl0025_module, "IN_SCOPE_MIN_INDEPENDENT_SUPPORTED", 5)

    with pytest.raises(SystemExit):
        runner.run_verify()


# ---------------------------------------------------------------------------
# Digest-schema hardening: missing schema fails closed instead of silently
# skipping validation; digest file-name-set drift is caught independently of
# the schema (a permissive/tampered schema must not defeat it).
# ---------------------------------------------------------------------------


def test_run_verify_fails_closed_on_missing_artifact_digests_schema(
    runner: Any, tmp_path: Path
) -> None:
    _copy_retained_package(runner, tmp_path)
    runner.ARTIFACT_DIGESTS_SCHEMA_PATH.unlink()

    with pytest.raises(SystemExit):
        runner.run_verify()


def test_run_verify_fails_closed_on_missing_decision_input_schema(
    runner: Any, tmp_path: Path
) -> None:
    _copy_retained_package(runner, tmp_path)
    runner.DECISION_INPUT_SCHEMA_PATH.unlink()

    with pytest.raises(SystemExit):
        runner.run_verify()


def test_run_verify_fails_closed_on_digest_set_drift_even_with_permissive_schema(
    runner: Any, tmp_path: Path
) -> None:
    _copy_retained_package(runner, tmp_path)

    # Weaken the digest schema to accept any object shape -- proving the
    # file-name-set check does not depend on the schema being strict.
    runner.ARTIFACT_DIGESTS_SCHEMA_PATH.write_text(
        json.dumps({"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "object"}),
        encoding="utf-8",
    )

    artifact_digests = json.loads(runner.ARTIFACT_DIGESTS_PATH.read_bytes())
    del artifact_digests["digests"]["REPORT.md"]
    _write_json(runner.ARTIFACT_DIGESTS_PATH, artifact_digests)

    with pytest.raises(SystemExit):
        runner.run_verify()
